config/routes.rb
Rails.application.routes.draw do
  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
  @people = Person.all
end

def show
  @person = Person.find(params[:id])
end

def new
  @person = Person.new
end

def edit
  @person = Person.find(params[:id])
end

def create
  @person = Person.new(person_params)

  if @person.save
    redirect_to people_path
  else
    render :new
  end
end

def update
@person = Person.find(params[:id])

if @person.update(person_params)
  redirect_to people_path
else
  render :edit
end
end

def destroy
People.find(params[:id]).destroy
redirect_to person_path
end

private

  def person_params
    params.require(:person).permit(:name, :age, :hair_color, :eye_color, :gender, :alive)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_navbar.html.erb
<p><%= link_to 'Add Another Person', new_person_path %></p>
<%= link_to 'View All', people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
<%= form_for @person do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :age %>
<%= f.text_field :age %>

<%= f.label :hair_color %>
<%= f.text_area :hair_color %>

<%= f.label :eye_color %>
<%= f.text_area :eye_color %>

<%= f.label :gender %>
<%= f.select :gender, options_for_select([' ', 'female', 'male', 'other'])%>

<%= f.label :alive %>
<%= f.select :alive, options_for_select([' ', 'Yes', 'No'])%>

<%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h1>
  People List
</h1>
<% @people.each do |person| %>
  <h2><%= person.name %></h2>
  <%= link_to 'Show People', person_path(person) %>
  <%= link_to 'Edit Person', edit_person_path(person) %>
  <%= link_to 'Delete Person', person, method: :delete %>
<% end %>

app/views/people/new.html.erb
<h1>Add New Person</h1>
<%= form_for @person do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :age %>
<%= f.text_field :age %>

<%= f.label :hair_color %>
<%= f.text_area :hair_color %>

<%= f.label :eye_color %>
<%= f.text_area :eye_color %>

<%= f.label :gender %>
<%= f.select :gender, options_for_select([' ', 'female', 'male', 'other'])%>

<%= f.label :alive %>
<%= f.select :alive, options_for_select([' ', 'Yes', 'No'])%>

<%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>
<p><%= @person.age %></p>
<p><%= @person.hair_color %></p>
<p><%= @person.eye_color %></p>
<p><%= @person.gender %></p>
<p><%= @person.alive %></p>
<%= link_to 'Back', people_path %>